[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins", "alloc"]

[build]
target = "x86_64-nu_os.json"

[target.'cfg(target_os = "none")']
runner = "cargo run --package boot --"

[alias]
kbuild = "build --target x86_64-nu_os.json -Zbuild-std=core -Zbuild-std-features=compiler-builtins-mem"
kimage = "run --target x86_64-nu_os.json -Zbuild-std=core -Zbuild-std-features=compiler-builtins-mem -- --no-run"
krun = "run --target x86_64-nu_os.json -Zbuild-std=core -Zbuild-std-features=compiler-builtins-mem"
ktest = "test --target x86_64-nu_os.json -Zbuild-std=core -Zbuild-std-features=compiler-builtins-mem"